var teamCodesToNames={
POR : ['Portland Trail Blazers'],
BOS : ['Boston Celtics'],
ROC : ['Rochester Royals', 'SAC'],
KCO : ['Kansas City-Omaha Kings', 'SAC'],
KCK : ['Kansas City Kings', 'SAC'],
CIN : ['Cincinnati Royals', 'SAC'],
SAC : ['Sacramento Kings'],
MIL : ['Milwaukee Bucks'],
PHI : ['Philadelphia 76ers'],
SYR : ['Syracuse Nationals', 'PHI'],
SDR : ['San Diego Rockets', 'HOU'],
HOU : ['Houston Rockets'],
SEA : ['Seattle SuperSonics', 'OKC'],
OKC : ['Oklahoma City Thunder'],
LAC : ['Los Angeles Clippers'],
BUF : ['Buffalo Braves', 'LAC'],
SDC : ['San Diego Clippers', 'LAC'],
MNL : ['Minneapolis Lakers', 'LAL'],
LAL : ['Los Angeles Lakers'],
DEN : ['Denver Nuggets'],
DNR : ['Denver Rockets', 'DEN'],
DNA : ['Denver Nuggets'],
MEM : ['Memphis Grizzlies'],
VAN : ['Vancouver Grizzlies', 'MEM'],
ORL : ['Orlando Magic'],
DAL : ['Dallas Mavericks'],
ATL : ['Atlanta Hawks'],
STL : ['St. Louis Hawks', 'ATL'],
TRI : ['Tri-Cities Blackhawks', 'ATL'],
MLH : ['Milwaukee Hawks', 'ATL'],
SFW : ['San Francisco Warriors', 'GSW'],
GSW : ['Golden State Warriors'],
PHW : ['Philadelphia Warriors', 'GSW'],
IND : ['Indiana Pacers'],
PIT : ['Pittsburgh Ironmen'],
BLB : ['Baltimore Bullets'],
STB : ['St. Louis Bombers'],
DET : ['Detroit Pistons'],
FTW : ['Fort Wayne Pistons', 'DET'],
NYK : ['New York Knicks'],
CHZ : ['Chicago Zephyrs', 'WAS'],
WSB : ['Washington Bullets', 'WAS'],
CHP : ['Chicago Packers', 'WAS'],
BAL : ['Baltimore Bullets', 'WAS'],
WAS : ['Washington Wizards'],
CAP : ['Capital Bullets', 'WAS'],
TOR : ['Toronto Raptors'],
PHO : ['Phoenix Suns'],
SSL : ['Spirits of St. Louis'],
CAR : ['Carolina Cougars', 'SSL'],
HSM : ['Houston Mavericks', 'SSL'],
SDS : ['San Diego Sails'],
SDA : ['San Diego Conquistadors', 'SDS'],
NJN : ['New Jersey Nets', 'BRK'],
NYN : ['New York Nets', 'BRK'],
NJA : ['Brooklyn Nets', 'BRK'],
NJA : ['New Jersey Americans', 'BRK'],
CHO : ['Charlotte Hornets'],
CHA : ['Charlotte Bobcats', 'CHO'],
CHI : ['Chicago Bulls'],
UTA : ['Utah Jazz'],
NOJ : ['New Orleans Jazz', 'UTA'],
MIN : ['Minnesota Timberwolves'],
MIA : ['Miami Heat'],
DLC : ['Dallas Chaparrals', 'SAS'],
TEX : ['Texas Chaparrals', 'SAS'],
SAS : ['San Antonio Spurs'],
SAA : ['San Antonio Spurs'],
NOK : ['New Orleans/Oklahoma City Hornets', 'NOP'],
NOH : ['New Orleans Hornets', 'NOP'],
NOP : ['New Orleans Pelicans'],
KEN : ['Kentucky Colonels'],
CLE : ['Cleveland Cavaliers'],
FLO : ['The Floridians'],
MMF : ['Miami Floridians', 'FLO'],
MNM : ['Minnesota Muskies', 'FLO'],
NOK : ['New Orleans/Oklahoma City Hornets'],
NOK : ['New Orleans Hornets'],
NOK : ['New Orleans Pelicans'],
OAK : ['Oakland Oaks', 'VIR'],
WSA : ['Washington Capitols', 'VIR'],
VIR : ['Virginia Squires'],
UTS : ['Utah Stars'],
LAS : ['Los Angeles Stars', 'UTS'],
ANA : ['Anaheim Amigos', 'UTS'],
PTP : ['Pittsburgh Pipers', 'PTC'],
MNP : ['Minnesota Pipers', 'PTC'],
PTC : ['Pittsburgh Condors'],
MMP : ['Memphis Pros', 'MMS'],
MMS : ['Memphis Sounds'],
NOB : ['New Orleans Buccaneers', 'MMS'],
MMT : ['Memphis Tams', 'MMS'],
DTF : ['Detroit Falcons'],
CHS : ['Chicago Stags'],
INO : ['Indianapolis Olympians'],
WSC : ['Washington Capitols'],
DNN : ['Denver Nuggets'],
CLR : ['Cleveland Rebels'],
PRO : ['Providence Steam Rollers'],
TRH : ['Toronto Huskies'],
INJ : ['Indianapolis Jets'],
AND : ['Anderson Packers'],
WAT : ['Waterloo Hawks'],
SHE : ['Sheboygan Red Skins'] }

var activeTeams = {
	'ATL' : 'Hawks',
	'BOS' : 'Celtrics',
	'NJN' : 'Nets',
	'CHA' : 'Hornets',
	'CHI' : 'Bulls',
	'CLE' : 'Cavaliers',
	'DAL' : 'Mavericks',
	'DEN' : 'Nuggets',
	'DET' : 'Pistons',
	'GSW' : 'Warriors',
	'HOU' : 'Rockets',
	'IND' : 'Pacers',
	'LAC' : 'Clippers',
	'LAL' : 'Lakers',
	'MEM' : 'Grizzlies',
	'MIA' : 'Heat',
	'MIL' : 'Bucks',
	'MIN' : 'Timberwolves',
	'NOH' : 'Hornets',
	'NYK' : 'Knicks',
	'OKC' : 'Thunder',
	'ORL' : 'Magic',
	'PHI' : '76ers',
	'PHO' : 'Suns',
	'POR' : 'Trailblazers',
	'SAC' : 'Kings',
	'SAS' : 'Spurs',
	'TOR' : 'Raptors',
	'UTA' : 'Jazz',
	'WAS' : 'Wizards'
}